'use client';
import { useEffect,useState,type FormEvent,type ReactNode } from 'react';
import Link from 'next/link';
import { EmploymentType,Gender,StaffPosition,type EmploymentType as EmploymentTypeValue,type Gender as GenderValue,type StaffPosition as StaffPositionValue } from '@nemis-desktop/types';
import { Badge,Button,EmptyState,ErrorState,Input,Modal,Select,Skeleton } from '@nemis-desktop/ui';
import { useViewModel } from '@/hooks/use-view-model';
import { useAcademicFoundationViewModel,useSettingsViewModel,useTeacherProfileViewModel,useTeacherSearchViewModel,useTeachersListViewModel,useTeachingAssignmentViewModel } from '@/lib/presentation/hooks';
const human=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const queryId=()=>typeof window==='undefined'?'':new URLSearchParams(window.location.search).get('id')??'';
function Page({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <div className="p-6 space-y-5"><div className="flex justify-between items-center gap-3"><div><h1 className="text-2xl font-semibold">{title}</h1><p className="text-sm text-slate-500">Offline teacher and assignment records stored on this device.</p></div>{action}</div>{children}</div>}
const rows=<T,>(state:{status:string;data?:readonly T[]})=>(state.status==='success'||state.status==='refreshing')?state.data??[]:[];

export function TeachersDirectoryPage(){
  const vm=useTeachersListViewModel(),search=useTeacherSearchViewModel(),foundation=useAcademicFoundationViewModel();
  const list=useViewModel(vm.store,s=>s.list),p=useViewModel(vm.store,s=>s.pagination),filters=useViewModel(vm.store,s=>s.filters),selected=useViewModel(vm.selection,s=>s.selectedIds);
  const subjects=useViewModel(foundation.store,s=>s.subjects),classes=useViewModel(foundation.store,s=>s.classes),years=useViewModel(foundation.store,s=>s.academicYears);
  useEffect(()=>{void vm.loadTeachers();void foundation.loadAcademicYears();void foundation.loadClasses();void foundation.loadSubjects();},[vm,foundation]);
  const update=(next:typeof filters)=>{search.setFilters(next);void search.search();};
  return <Page title="Teachers & Staff" action={<Link href="/government/school-admin/teachers-staff/create"><Button>Add teacher</Button></Link>}>
    <div className="bg-white border rounded-card p-4 grid md:grid-cols-4 gap-3">
      <Input placeholder="Name or employee number" defaultValue={filters.keyword} onChange={e=>search.setKeyword(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search.search();}}/>
      <Select options={[{value:'',label:'All employment types'},...Object.values(EmploymentType).map(v=>({value:v,label:human(v)}))]} value={filters.employmentType??''} onChange={e=>update({...filters,employmentType:(e.target.value||undefined) as EmploymentTypeValue|undefined})}/>
      <Select options={[{value:'',label:'All subjects'},...rows(subjects).map(v=>({value:v.id,label:v.name}))]} value={filters.subjectId??''} onChange={e=>update({...filters,subjectId:e.target.value||undefined})}/>
      <Select options={[{value:'',label:'All academic years'},...rows(years).map(v=>({value:v.id,label:v.code}))]} value={filters.academicYearId??''} onChange={e=>update({...filters,academicYearId:e.target.value||undefined})}/>
      <Select options={[{value:'',label:'All classes'},...rows(classes).map(v=>({value:v.id,label:`${v.name} — ${human(v.gradeLevel)}`}))]} value={filters.classId??''} onChange={e=>update({...filters,classId:e.target.value||undefined})}/>
      <Select options={[{value:'active',label:'Active'},{value:'archived',label:'Archived'},{value:'all',label:'All statuses'}]} value={filters.isActive===undefined?'all':filters.isActive?'active':'archived'} onChange={e=>update({...filters,isActive:e.target.value==='all'?undefined:e.target.value==='active'})}/>
      <Button variant="secondary" onClick={()=>void search.search()}>Search</Button>
      {selected.size>0&&<Button variant="destructive" onClick={()=>void vm.bulkArchive([...selected])}>Archive selected ({selected.size})</Button>}
    </div>
    {(list.status==='loading'||list.status==='idle')&&<Skeleton className="h-64 w-full"/>}
    {list.status==='error'&&<ErrorState message={list.error.userMessage} onRetry={()=>void vm.loadTeachers()}/>}
    {list.status==='empty'&&<EmptyState title={filters.keyword?'No matching search results.':'No teachers found.'} description="Create a teacher to build your school's teaching structure." action={<Link href="/government/school-admin/teachers-staff/create"><Button>Add teacher</Button></Link>}/>}
    {(list.status==='success'||list.status==='refreshing')&&<><div className="overflow-x-auto bg-white border rounded-card"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3"></th><th>Name</th><th>Employee ID</th><th>Position</th><th>Employment</th><th>Status</th><th></th></tr></thead><tbody>{list.data.map(t=><tr key={t.id} className="border-b"><td className="p-3"><input type="checkbox" checked={selected.has(t.id)} onChange={()=>vm.toggleSelection(t.id)}/></td><td>{t.fullName}</td><td>{t.employeeNumber}</td><td>{human(t.position)}</td><td>{human(t.employmentType)}</td><td><Badge variant={t.isActive?'success':'neutral'}>{t.isActive?'Active':'Archived'}</Badge></td><td><Link className="text-blue-700" href={`/government/school-admin/teachers-staff/profile?id=${t.id}`}>View</Link></td></tr>)}</tbody></table></div><div className="flex justify-between text-sm text-slate-500"><span>{p.totalCount} teachers</span><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={p.page<=1} onClick={()=>void vm.goToPage(p.page-1)}>Previous</Button><Button size="sm" variant="secondary" disabled={p.page*p.pageSize>=p.totalCount} onClick={()=>void vm.goToPage(p.page+1)}>Next</Button></div></div></>}
  </Page>;
}

export function TeacherFormPage({edit=false}:{edit?:boolean}){
  const list=useTeachersListViewModel(),profileVm=useTeacherProfileViewModel(),settings=useSettingsViewModel();
  const school=useViewModel(settings.store,s=>s.profile),profileState=useViewModel(profileVm.store,s=>s.profile);
  const [id,setId]=useState(''),[first,setFirst]=useState(''),[middle,setMiddle]=useState(''),[last,setLast]=useState(''),[employee,setEmployee]=useState(''),[dob,setDob]=useState(''),[gender,setGender]=useState<GenderValue>(Gender.FEMALE),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[address,setAddress]=useState(''),[position,setPosition]=useState<StaffPositionValue>(StaffPosition.TEACHER),[employment,setEmployment]=useState<EmploymentTypeValue>(EmploymentType.FULL_TIME),[joining,setJoining]=useState(new Date().toISOString().slice(0,10)),[qualification,setQualification]=useState('');
  useEffect(()=>{void settings.loadCurrentSchool();const value=queryId();setId(value);if(edit&&value)void profileVm.loadProfile(value);},[settings,profileVm,edit]);
  useEffect(()=>{if(edit&&(profileState.status==='success'||profileState.status==='refreshing')){const d=profileState.data;setFirst(d.firstName);setMiddle(d.middleName??'');setLast(d.lastName);setEmployee(d.employeeNumber);setDob(d.dateOfBirth.slice(0,10));setGender(d.gender);setPhone(d.phoneNumber);setEmail(d.email??'');setAddress(d.address??'');setPosition(d.position);setEmployment(d.employmentType);setJoining(d.dateOfJoining.slice(0,10));setQualification(typeof d.qualifications?.summary==='string'?d.qualifications.summary:'');}},[edit,profileState]);
  const submit=async(e:FormEvent)=>{e.preventDefault();const common={firstName:first,middleName:middle||undefined,lastName:last,dateOfBirth:dob,gender,phoneNumber:phone,email:email||undefined,address:address||undefined,employeeNumber:employee,position,employmentType:employment,dateOfJoining:joining,qualifications:qualification?{summary:qualification}:undefined};const result=edit?await profileVm.updateTeacher({teacherId:id,...common}):(school.status==='success'||school.status==='refreshing'?await list.createTeacher({institutionId:school.data.id,...common}):null);if(result?.ok)window.location.href=`/government/school-admin/teachers-staff/profile?id=${result.data.id}`;};
  return <Page title={edit?'Edit Teacher':'Create Teacher'}><form onSubmit={e=>void submit(e)} className="bg-white border rounded-card p-6 space-y-4 max-w-4xl">
    <div className="grid md:grid-cols-3 gap-3"><Input label="First name" required value={first} onChange={e=>setFirst(e.target.value)}/><Input label="Middle name" value={middle} onChange={e=>setMiddle(e.target.value)}/><Input label="Last name" required value={last} onChange={e=>setLast(e.target.value)}/></div>
    <div className="grid md:grid-cols-2 gap-3"><Input label="Employee number" required value={employee} onChange={e=>setEmployee(e.target.value)}/><Input label="Date of birth" type="date" required value={dob} onChange={e=>setDob(e.target.value)}/><Select label="Gender" options={Object.values(Gender).map(v=>({value:v,label:human(v)}))} value={gender} onChange={e=>setGender(e.target.value as GenderValue)}/><Select label="Position" options={Object.values(StaffPosition).map(v=>({value:v,label:human(v)}))} value={position} onChange={e=>setPosition(e.target.value as StaffPositionValue)}/><Select label="Employment type" options={Object.values(EmploymentType).map(v=>({value:v,label:human(v)}))} value={employment} onChange={e=>setEmployment(e.target.value as EmploymentTypeValue)}/><Input label="Date joined" type="date" required value={joining} onChange={e=>setJoining(e.target.value)}/><Input label="Phone" required value={phone} onChange={e=>setPhone(e.target.value)}/><Input label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></div>
    <Input label="Address" value={address} onChange={e=>setAddress(e.target.value)}/><Input label="Qualification summary" value={qualification} onChange={e=>setQualification(e.target.value)}/>
    {school.status==='empty'&&!edit&&<p className="text-sm text-red-700">A school profile must be provisioned before teachers can be created.</p>}<div className="flex gap-2"><Button type="submit">Save teacher</Button><Link href="/government/school-admin/teachers-staff"><Button type="button" variant="secondary">Cancel</Button></Link></div>
  </form></Page>;
}

export function TeacherProfilePage(){
  const profileVm=useTeacherProfileViewModel(),assignVm=useTeachingAssignmentViewModel(),foundation=useAcademicFoundationViewModel();
  const state=useViewModel(profileVm.store,s=>s.profile),assignments=useViewModel(assignVm.store,s=>s.assignments),classes=useViewModel(foundation.store,s=>s.classes),subjects=useViewModel(foundation.store,s=>s.subjects);
  const [id,setId]=useState(''),[open,setOpen]=useState(false),[classId,setClassId]=useState(''),[subjectId,setSubjectId]=useState(''),[homeroom,setHomeroom]=useState(false);
  useEffect(()=>{const value=queryId();setId(value);if(value){void profileVm.loadProfile(value);void assignVm.load(value);}void foundation.loadClasses();void foundation.loadSubjects();},[profileVm,assignVm,foundation]);
  if(state.status==='loading'||state.status==='idle')return <Page title="Teacher Profile"><Skeleton className="h-64 w-full"/></Page>;
  if(state.status==='error')return <Page title="Teacher Profile"><ErrorState message={state.error.userMessage}/></Page>;
  if(state.status==='empty')return <Page title="Teacher Profile"><EmptyState title="Teacher not found."/></Page>;
  const d=state.data;
  const facts: Array<[string,string]>=[['Employee ID',d.employeeNumber],['Position',human(d.position)],['Employment',human(d.employmentType)],['Date joined',d.dateOfJoining.slice(0,10)],['Phone',d.phoneNumber],['Email',d.email??'—'],['Address',d.address??'—'],['Status',d.isActive?'Active':'Archived']];
  const submit=async(e:FormEvent)=>{e.preventDefault();const r=await assignVm.assign({teacherId:id,classId,subjectId,isClassTeacher:homeroom});if(r.ok){setOpen(false);setClassId('');setSubjectId('');}};
  return <Page title={d.fullName} action={<div className="flex gap-2"><Link href={`/government/school-admin/teachers-staff/edit?id=${id}`}><Button variant="secondary">Edit</Button></Link><Button onClick={()=>setOpen(true)} disabled={!d.isActive}>Assign teaching</Button><Button variant={d.isActive?'destructive':'secondary'} onClick={()=>void profileVm.setActive(id,!d.isActive)}>{d.isActive?'Archive':'Restore'}</Button></div>}>
    <div className="grid lg:grid-cols-3 gap-4"><section className="lg:col-span-2 bg-white border rounded-card p-6 grid sm:grid-cols-2 gap-4">{facts.map(([l,v])=><Fact key={l} label={l} value={v}/>)}</section><section className="bg-white border rounded-card p-6"><h2 className="font-semibold">Teacher Summary</h2><p className="text-sm mt-3">{rows(assignments).length} active assignment(s)</p><p className="text-sm mt-2">Approval: {human(d.approvalStatus)}</p><p className="text-sm mt-2">Qualifications: {typeof d.qualifications?.summary==='string'?d.qualifications.summary:'Not recorded'}</p></section></div>
    <section className="bg-white border rounded-card p-6"><h2 className="font-semibold mb-3">Teaching Assignments</h2>{assignments.status==='empty'?<p className="text-sm text-slate-500">No teaching assignments.</p>:assignments.status==='success'||assignments.status==='refreshing'?<div className="space-y-2">{assignments.data.map(a=><div key={a.id} className="grid md:grid-cols-6 gap-2 items-center border-b py-3 text-sm"><span>{a.academicYearName}</span><span>{human(a.gradeLevel)}</span><span>{a.className}{a.section?` — ${a.section}`:''}</span><span>{a.subjectName??'Homeroom'}</span><span>{a.isClassTeacher?'Class teacher':'Subject teacher'}</span><Button size="sm" variant="destructive" onClick={()=>void assignVm.remove(a.id,id)}>Remove</Button></div>)}</div>:<Skeleton className="h-20 w-full"/>}</section>
    <div className="grid md:grid-cols-2 gap-4"><EmptyState title="Assignment History" description="Historical assignment snapshots will appear when the backend exposes an assignment-history model."/><EmptyState title="Teacher Documents" description="Document storage is reserved for a future phase."/><EmptyState title="Teacher Activity Timeline" description="Synchronized activity events will appear here in a future phase."/><EmptyState title="Payroll" description="Payroll is outside this phase."/><EmptyState title="Leave Management" description="Leave management is outside this phase."/></div>
    <Modal isOpen={open} onClose={()=>setOpen(false)} title="Assign Teacher" footer={<Button form="assignment-form" type="submit" disabled={!classId||!subjectId}>Save assignment</Button>}><form id="assignment-form" onSubmit={e=>void submit(e)} className="space-y-3"><Select label="Class / section" required placeholder="Select class" value={classId} onChange={e=>setClassId(e.target.value)} options={rows(classes).filter(v=>v.isActive).map(v=>({value:v.id,label:`${v.name} — ${human(v.gradeLevel)}`}))}/><Select label="Subject" required placeholder="Select subject" value={subjectId} onChange={e=>setSubjectId(e.target.value)} options={rows(subjects).filter(v=>v.isActive).map(v=>({value:v.id,label:v.name}))}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={homeroom} onChange={e=>setHomeroom(e.target.checked)}/>Make this teacher the homeroom / class teacher</label></form></Modal>
  </Page>;
}
function Fact({label,value}:{label:string;value:string}){return <div><p className="text-xs uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1">{value}</p></div>;}
