'use client';

import { usePresentation } from './presentation-provider';

export const useDashboardViewModel = () => usePresentation().viewModels.dashboard;
export const useStudentsViewModel = () => usePresentation().viewModels.students;
export const useStudentsListViewModel = () => usePresentation().viewModels.studentsList;
export const useStudentProfileViewModel = () => usePresentation().viewModels.studentProfile;
export const useEnrollmentViewModel = () => usePresentation().viewModels.enrollment;
export const useStudentSearchViewModel = () => usePresentation().viewModels.studentSearch;
export const useSettingsViewModel = () => usePresentation().viewModels.settings;
export const useDeviceViewModel = () => usePresentation().viewModels.device;
export const useCurrentUserViewModel = () => usePresentation().viewModels.currentUser;
export const useSyncViewModel = () => usePresentation().viewModels.sync;
export const useConnectivityStore = () => usePresentation().stores.connectivity;
export const useNotificationStore = () => usePresentation().stores.notifications;
export const useAcademicYearViewModel = () => usePresentation().viewModels.academicYear;
export const useAcademicFoundationViewModel = () => usePresentation().viewModels.academicFoundation;
export const useBootstrapStore = () => usePresentation().stores.bootstrap;
export const useTeachersListViewModel = () => usePresentation().viewModels.teachersList;
export const useTeacherProfileViewModel = () => usePresentation().viewModels.teacherProfile;
export const useTeacherSearchViewModel = () => usePresentation().viewModels.teacherSearch;
export const useTeachingAssignmentViewModel = () => usePresentation().viewModels.teachingAssignments;
export const useTeacherDashboardViewModel = () => usePresentation().viewModels.teacherDashboard;
export const useTimetableViewModel = () => usePresentation().viewModels.timetable;
export const useTeacherScheduleViewModel = () => usePresentation().viewModels.teacherSchedule;
export const useClassScheduleViewModel = () => usePresentation().viewModels.classSchedule;
export const useSubjectScheduleViewModel = () => usePresentation().viewModels.subjectSchedule;
export const useTimetableConflictViewModel = () => usePresentation().viewModels.timetableConflicts;
export const useTimetableDashboardViewModel = () => usePresentation().viewModels.timetableDashboard;
export const useAttendanceViewModel = () => usePresentation().viewModels.attendance;
export const useClassRosterViewModel = () => usePresentation().viewModels.classRoster;
